### ISSUE TITLE
Recommend new score evaluation method

### ISSUE THREAD

**Issue by torquedrop** [impel-intelligence/dippy-bittensor-subnet#82] opened 2024-10-14 02:58 UTC
I recommend using the `truncated mean` scoring system. In this system, the highest and lowest scores are removed, and the average of the remaining scores is used to calculate the final result. To save time during score evaluation, consider reducing the sample size to 1024 or 512 for each scoring instance, and limiting the number of score calculations to 5.

**Comment by donaldknoller** [comment] 2024-10-14 18:08
Closing as duplicate of https://github.com/impel-intelligence/dippy-bittensor-subnet/issues/80

**Closed by donaldknoller** 2024-10-14 18:08 UTC
